### ISSUE TITLE
SOAP Response Forbidden

### ISSUE THREAD

**Issue by janstuemmel** [emgag/vg-wort-message-api#1]
I'am trying to submit a new messages to VG-Wort via your client, but a always get the response `[HTTP] Forbidden`. I then tryed the checkAuthor route and got the same result:

```php

use Emgag\VGWort\MessageService\MessageService;
use Emgag\VGWort\MessageService\checkAuthorRequest;

// ... vars

$messageService = new MessageService([
  "authentication"     => SOAP_AUTHENTICATION_BASIC,
  "login"              => $username,
  "password"           => $password,
  "connection_timeout" => 60
]);

$checkAuthorRequest = new checkAuthorRequest($cardNo, $firstName, $surName);

$response = $messageService->checkAuthor($checkAuthorRequest);

var_dump($response);
```

do you have any idea why this happens?

**Comment by janstuemmel** [comment]
This is probably due account limitations, only publisher accounts have "webServices" access. 

WTF vgwort :angry: we're not living in 00ers

**Comment by maetthu** [comment]
It's not like SOAP is particularly modern either :wink: good to know!
